### PR TITLE
Adding hamburger menu

### LINKED ISSUE #4: Hamburger
Add hamburger icon for toggling the menu on mobile (instead of button "menu")

### PR DESCRIPTION
**Pull request by vncsalencar**
Fix #4

### CODE REVIEW

**Comment by pniedzwiedzinski** [comment]
Thanks @vncsalencar.
It would be better though if you do that with css, instead of svg. I was thinking something like this: https://codepen.io/pniedzwiedzinski/pen/YzKRVgw

**Comment by vncsalencar** [comment]
Oh, okay! Tomorrow I'll do it right this time. @pniedzwiedzinski

**Comment by pniedzwiedzinski** [comment]
Hey @vncsalencar, what's the status?

**Comment by vncsalencar** [comment]
Sorry! I had some problems and got locked out of my account with only access to my previously cloned repositories. I'll do it by this weekend at most. Really sorry.

**Comment by pniedzwiedzinski** [comment]
Not a problem ;)

**Comment by pniedzwiedzinski** [comment]
@vncsalencar are you still going to do this?

**Comment by pniedzwiedzinski** [comment]
Since it's stale for over a month I'm closing it

**Pull request closed without merging**
